### ISSUE TITLE
Poetry/pyproject.toml support?

### ISSUE THREAD

**Issue by macintacos** [Twixes/pypi-assistant#10]
I use Poetry for dependency management in several projects. Any chance this could be added?

Docs: https://python-poetry.org/docs/dependency-specification/

**Comment by Twixes** [comment]
I've actually looked into this a while ago, but unfortunately parsing TOML reliably for the purposes of this extension would be considerably more complex than it is with pip requirements files. While I don't have the time to work on this myself, I'd be very happy to accept a nice implementation.

**Comment by mrijken** [comment]
Did you look at https://www.npmjs.com/package/toml? It can convert the toml in a regular json object.

**Comment by alex-way** [comment]
For inspiration, the following project does exactly what's been requested here: <https://github.com/ninoseki/vscode-pylens>

I'll take a quick look to see if I'm able to put something cohesive together

**Comment by Zerotask** [comment]
This would be a nice addition, since Poetry is getting more ground recently.

A little thing to consider, you can define groups in poetry. In our case we have `[tool.poetry.dependencies]` and `[tool.poetry.group.dev.dependencies]`
