### ISSUE TITLE
Doesn't work: It shows "no commands" under each line in requirements.txt

### ISSUE THREAD

**Issue by randomsnowflake** [Twixes/pypi-assistant#15]
I just installed and activated the add-on in my Django project.

However, it doesn't work. It doesn't show a hover effect or the version numbers. The only thing it does is add a gray "no commands" line under each pip package.

Please see the attached screenshot.

<img width="2168" alt="Screenshot 2023-01-20 at 17 24 33" src="https://user-images.githubusercontent.com/11420149/213673253-756d7306-ba0d-41a6-946f-8dde3787bae6.png">

**Comment by Twixes** [comment]
Hi @randomsnowflake! Were you offline at the time, or were experiencing any internet connection issues? That is the most likely cause of "no commands" showing up. I can't reproduce this otherwise.

**Comment by randomsnowflake** [comment]
I have internet connectivity & All other services work fine.

However I'm located in Thailand and my ping time to European servers is about 200ms. Maybe that's too much? The "no commands" pop up about three seconds after starting VSCode.

I tried again using 5G data, as well as with a European VPN. Same problem.

**Comment by Twixes** [comment]
It's been a while and there have been no other reports of this, so I'll close. Let me know if this is still an issue.
