### ISSUE TITLE
Carve new release

### ISSUE THREAD

**Issue by alex-way** [Twixes/pypi-assistant#26]
Hey Twixes,

Could you carve a new release when you get a chance 😄 I'd love to see the new features out in the wild!

Thanks, Alex.

**Comment by Twixes** [comment]
Done, now that 2.0.0 with Poetry support is now live!

Sorry this took such a long time – I wanted to add proper test coverage for both `requirements.txt` and `pyproject.toml` parsing, which finally went in in https://github.com/Twixes/pypi-assistant/commit/ba75992fe4b6859decbbeda11798c74cfc60611c.
