### ISSUE TITLE
Feature Request: Set Hover delays for pypi-assistant specifically.

### ISSUE THREAD

**Issue by Jeff-Lowrey** [Twixes/pypi-assistant#28]
When I hover over a requirement in a pip file, it gives me the correct hover window.

But when I try to move my mouse to click on a link in the hover window - it (working as designed?) closes the hover window the second I move my mouse-pointer.

So I can't click on the links - because the hover disappears.

Globally, this is controlled by editor settings:
1. editor.hover.enabled
2. editor.hover.sticky
3. editor.hover.delay
4. editor.hover.hidingDelay

Both editor.hover.enabled and editor.hover.sticky must be set to True in order for the two delays to be active.

This is not obvious - and without understanding this, the pypi-assistant hovers can disappear too quickly to be useful.

However, these are global settings.  It would be useful if pypi-assistant had extension specific settings for these values.  This makes it immediately obvious how to control the delays, and clear that the delays are specific to this extension.

I don't know if the Language API lets you do this, thoiugh.

**Comment by Twixes** [comment]
Hi @Jeff-Lowrey, thanks for making the issue!
Hmm, it's your choice as a user whether you want to sticky hovers (the default behavior), so I don't think there's anything the extension can do if you chose to disable `editor.hover.sticky`. Why not enable it?
