### ISSUE TITLE
Feature Request: support for dependencies defined in pyproject.toml according to PEP 631

### ISSUE THREAD

**Issue by sylvain1811** [Twixes/pypi-assistant#30]
See 
- https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies.
- https://peps.python.org/pep-0631/
- https://packaging.python.org/en/latest/specifications/pyproject-toml/#pyproject-toml-spec

**Comment by Twixes** [comment]
Hi @sylvain1811! Thanks for this issue – I was unaware of PEP 631, but it definitely makes sense to recognize it. In fact it was barely any effort to add support, so I just published [version 2.1.0](https://github.com/Twixes/pypi-assistant/releases/tag/v2.1.0) of PyPI Assistant, which adds PEP 631 to the list of supported formats. :)

**Comment by sylvain1811** [comment]
Hi @Twixes, thank you very much! Good work!
