### ISSUE TITLE
Support multiple requirement.txt files with different names

### ISSUE THREAD

**Issue by BrendanSimon** [Twixes/pypi-assistant#6]
It would be great if your extension could support requirement.txt files with different names.

As an example I have two files in my repo to support a target embedded system and the host development system.

`pip_requirements_target.txt`
`pip_requirements_dev.txt`

I vscode setting to specify a list of valid requirement file names (regex/glob) would be nice :)
```json
setting = [ "*requirements*.txt", "my_stupid_req_file_name.txt" ]
```

Maybe `[ "*requirements*.txt" ]` could be the default?

**Comment by Twixes** [comment]
Hey! So actually this extension doesn't look at the filename. It activates for all files that VS Code determines to be of type `pip requirements`. That detection is built neither into VS Code, nor into PyPI assistant – it's actually handled by [Microsoft's official Python extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-python.python). I've found Microsoft's extension to do a pretty good job generally (detecting also things like `requirements.in` or `requirements-dev.txt`), but if it doesn't support a use case like `pip_requirements_dev.txt`, I suggest creating an issue in https://github.com/Microsoft/vscode-python/issues

**Comment by Twixes** [comment]
I suppose this is resolved? If not, feel free to reopen with details!
